fst_input_mode: "direct"
fst_autosomes: "data/example/qst_neutral_autosomes_validate.txt"
fst_chrX: "data/example/qst_neutral_chrX_validate.txt"
adaptive_qst_levels: [0.75]
ve_ratios: [1.0]
num_repeats: 6
num_neutral: 6
num_sim: 50000
batch_size: 3
threshold_percentile: 0.95
summary_stats_combos:
  - "QST,F_within_pop"
chromosomes: ["autosomes"]
sample_structures: []
output_dir: "results/evaluate"
threads_per_job: 1
