sample_structure: "data/example/sample_structure.csv"
trait_values: "data/example/trait_values_validate.csv"
fst_input_mode: "direct"
fst_autosomes: "data/example/qst_neutral_autosomes_validate.txt"
fst_chrX: "data/example/qst_neutral_chrX_validate.txt"
num_neutral: 6
num_sim: 10000
batch_size: 3
threshold_percentile: 0.95
summary_stats: "QST,F_within_pop"
chromosomes: ["autosomes"]
output_dir: "results/detect"
threads_per_job: 1
